### ISSUE TITLE
Unable to parse filename

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#156] opened 2019-11-14 20:02 UTC
I am trying to import sound files. I assume this is the first thing I do once I runserver up and running, although I am not sure. Unfortunately, I am unable to import data, as it is unable to parse the file name. I've tried these formats: 
- `NBNC_19-08-07_12.31.00_Z.wav`
- `NBNC_2019-08-07_12.31.00_Z.wav`

Here is the complete log.

```
(vesper-0.4.7) 14:58 ~/src/NBNC_Archive 🦉 vesper_admin runserver
Performing system checks...

System check identified no issues (0 silenced).
November 14, 2019 - 15:00:10
Django version 2.1.7, using settings 'vesper.django.project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Exception ignored in: <module 'threading' from '//anaconda3/envs/vesper-0.4.7/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/threading.py", line 1351, in _after_fork
    thread._reset_internal_locks(False)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/threading.py", line 805, in _reset_internal_locks
    self._started._reset_internal_locks()
AttributeError: 'bool' object has no attribute '_reset_internal_locks'
[14/Nov/2019 15:00:14] "POST /import-recordings/ HTTP/1.1" 302 0
[14/Nov/2019 15:00:14] "GET /jobs/7/ HTTP/1.1" 200 5781
[14/Nov/2019 15:00:14] "GET /static/vesper/view/job.js HTTP/1.1" 200 953
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54159)
[14/Nov/2019 15:00:14] "GET /static/vesper/view/job.css HTTP/1.1" 200 33
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54160)
Traceback (most recent call last):
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-11-14 15:00:19,067 WARNING  Preset manager encountered directory for unrecognized preset type "Classification Commands" at "/Users/richard/src/NBNC_Archive/Presets/Classification Commands".
2019-11-14 15:00:19,067 INFO     Job started for command "import" with arguments:
2019-11-14 15:00:19,068 INFO         {
2019-11-14 15:00:19,068 INFO             "importer": {
2019-11-14 15:00:19,069 INFO                 "name": "Recording Importer",
2019-11-14 15:00:19,070 INFO                 "arguments": {
2019-11-14 15:00:19,070 INFO                     "paths": [
2019-11-14 15:00:19,070 INFO                         "/Users/richard/src/NBNC_Archive/Recordings"
2019-11-14 15:00:19,071 INFO                     ],
2019-11-14 15:00:19,071 INFO                     "recursive": true,
2019-11-14 15:00:19,071 INFO                     "recording_file_parser": {
2019-11-14 15:00:19,071 INFO                         "name": "MPG Ranch Recording File Parser",
2019-11-14 15:00:19,071 INFO                         "arguments": {
2019-11-14 15:00:19,071 INFO                             "station_name_aliases_preset": "Station Name Aliases"
2019-11-14 15:00:19,071 INFO                         }
2019-11-14 15:00:19,071 INFO                     }
2019-11-14 15:00:19,071 INFO                 }
2019-11-14 15:00:19,071 INFO             }
2019-11-14 15:00:19,071 INFO         }
2019-11-14 15:00:19,076 ERROR    Recording import failed with an exception.
The exception message was:
    Error parsing recording file "/Users/richard/src/NBNC_Archive/Recordings/NBNC_19-08-07_12.31.00_Z.wav": Could not parse file name.
The archive was not modified.
See below for exception traceback.
2019-11-14 15:00:19,085 ERROR    Job raised exception. See traceback below.
Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 193, in _parse_recording_file
    file = self.file_parser.parse_file(str(file_path))
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/mpg_ranch/recording_file_parser.py", line 525, in parse_file
    self._parse_file_name(file_path)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/mpg_ranch/recording_file_parser.py", line 555, in _parse_file_name
    raise ValueError('Could not parse file name.')
ValueError: Could not parse file name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/job_runner.py", line 145, in run_job
    complete = command.execute(info)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/import_command.py", line 22, in execute
    return self._importer.execute(context)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 58, in execute
    recordings = self._get_recordings()
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 85, in _get_recordings
    self._get_path_recording_files(path) for path in self.paths))
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 85, in <genexpr>
    self._get_path_recording_files(path) for path in self.paths))
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 92, in _get_path_recording_files
    return self._get_dir_recording_files(path)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 107, in _get_dir_recording_files
    file = self._get_recording_file(Path(file_path))
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 126, in _get_recording_file
    file = self._parse_recording_file(abs_path)
  File "//anaconda3/envs/vesper-0.4.7/lib/python3.6/site-packages/vesper/command/recording_importer.py", line 198, in _parse_recording_file
    file_path, str(e)))
vesper.command.command.CommandExecutionError: Error parsing recording file "/Users/richard/src/NBNC_Archive/Recordings/NBNC_19-08-07_12.31.00_Z.wav": Could not parse file name.
```

**Comment by RichardLitt** [comment] 2019-11-14 20:07
Related to #107 and #140.

**Comment by HaroldMills** [comment] 2019-11-18 23:50
Before Vesper can import recordings into an archive, the archive must contain the station(s) for which the recordings will be imported, as well as the relevant recorder(s) and microphone(s). I am working on user documentation that explains this, and how to initialize an archive. Once an archive contains the appropriate station(s), recorder(s), and microphone(s), you can import recordings with file names of the form "NBNC_2019-08-07_12.31.00_Z.wav" into it. Vesper does not recognize file names of the form "NBNC_19-08-07_12.31.00_Z.wav", i.e. with two-digit instead of four-digit years.

**Comment by HaroldMills** [comment] 2019-11-18 23:54
I am closing this issue since it is more or less a duplicate of issue #107.

**Closed by HaroldMills** 2019-11-18 23:54 UTC
Labels: duplicate

**Comment by RichardLitt** [comment] 2019-11-19 13:54
Thanks, @HaroldMills.
