### ISSUE TITLE
localhost:8080/ redirects to /clip_calendar, which 404s without station_mic objects

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#157] opened 2019-11-14 20:04 UTC
`vesper_admin runserver` runs on localhost:8080. However, when I go to that address, it redirects to `http://127.0.0.1:8000/clip-calendar/`. This shows an error.
 
<img width="913" alt="Screen Shot 2019-11-14 at 15 04 03" src="https://user-images.githubusercontent.com/910753/68892018-055b2b00-06f0-11ea-8b1a-62ea846e1b97.png">

**Comment by hal4287** [comment] 2019-11-16 18:03
I have this same issue and can't figure it out.

**Comment by HaroldMills** [comment] 2019-11-18 23:41
Thanks, @RichardLitt and @hal4287, for reporting this issue. The problem occurs if one tries to look at a clip calendar for an empty archive. Before you can look at a clip calendar, you have to populate the archive with at least one station, recorder, microphone, detector, and annotation. I am working on better error messages for this situation and also user documentation that explains how to initialize an archive. Those will be available soon. I will close this issue since it duplicates issue #152.

**Comment by HaroldMills** [comment] 2019-11-18 23:42
Duplicate of issue #152.

**Closed by HaroldMills** 2019-11-18 23:42 UTC
Labels: enhancement
